# Generated by Django 2.1.4 on 2018-12-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migApp', '0003_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
