# Generated by Django 2.1.4 on 2018-12-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migApp', '0007_review_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggestions', models.TextField()),
            ],
        ),
    ]
